name: DeltaWarps
main: com.gmail.tracebachi.DeltaWarps.DeltaWarpsPlugin
version: 2.1.0
author: GeeItsZee (tracebachi@gmail.com)
depend: [SockExchange, DbShare, DeltaEssentials]
soft-depend: [Factions]
commands:
  warp:
    aliases: []
  serverwarp:
    aliases: [swarp]
